#{ gemspec.name } #{ "_#{ gemspec.summary }_" if gemspec.summary }
===

#{ gemspec.description }

Version: #{ gemspec.version }

Basic sample
---
#{ code.call "sample/a0.rb" }

[More samples](https://github.com/lpogic/modeling/tree/#{ gemspec.version.to_s[/\d+\.\d+/] }/doc/wiki)

Requirements
---
- Ruby version: #{ gemspec.required_ruby_version }

Installation
---
```
gem install #{ gemspec.name }
```

Authors
---
#{ gemspec.authors.zip(Array(gemspec.email)).map{ "- #{_1} (#{_2})" }.join("\n") }
