#{ gemspec.name }#{ " - #{ gemspec.summary }" if gemspec.summary }
===

#{ gemspec.description }

Basic sample
---
#{ code.call "sample/a0.rb" }

[More samples](https://github.com/lpogic/modeling/blob/main/doc/wiki/README.md)

Requirements
---
- Ruby version: #{ gemspec.required_ruby_version }

Installation
---
```
gem install #{ gemspec.name }
```

Authors
---
#{ gemspec.authors.zip(Array(gemspec.email)).map{ "- #{_1} (#{_2})" }.join("\n") }
