#{ gemspec.name }#{ " - #{ gemspec.summary }" if gemspec.summary }
===

#{ gemspec.description }

Basics
---
#{ code.call "sample/a0.rb" }

Installation
---
```
gem install #{ gemspec.name }
```

Usage
---
[Wiki](https://github.com/lpogic/modeling/blob/main/doc/wiki/README.md)

Authors
---
#{ gemspec.authors.zip(Array(gemspec.email)).map{ "- #{_1} (#{_2})" }.join("\n") }
